# Generated by Django 5.2.1 on 2025-05-15 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('RPG', 'RPG'), ('FPS', 'FPS'), ('VN', 'Visual Novel'), ('MET', 'Metroidvania')], max_length=20)),
                ('mood', models.CharField(choices=[('CYBERPUNK', 'Cyberpunk'), ('DARK', 'Dark Fantasy'), ('DREAMY', 'Onirique'), ('POSTAPO', 'Post-apocalyptique')], max_length=20)),
                ('keywords', models.CharField(max_length=200)),
                ('references', models.CharField(blank=True, max_length=200, null=True)),
                ('universe_description', models.TextField(blank=True)),
                ('main_story', models.TextField(blank=True)),
                ('characters', models.JSONField(blank=True, null=True)),
                ('locations', models.JSONField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
