# Generated by Django 5.2.1 on 2025-05-14 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("RPG", "Role-Playing Game"),
                            ("FPS", "First-Person Shooter"),
                            ("METROIDVANIA", "Metroidvania"),
                            ("VISUAL_NOVEL", "Visual Novel"),
                            ("PLATFORMER", "Platformer"),
                            ("STRATEGY", "Strategy"),
                            ("SIMULATION", "Simulation"),
                            ("PUZZLE", "Puzzle"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ambiance",
                    models.CharField(
                        choices=[
                            ("POST_APOCALYPTIC", "Post-Apocalyptic"),
                            ("CYBERPUNK", "Cyberpunk"),
                            ("FANTASY", "Fantasy"),
                            ("DARK_FANTASY", "Dark Fantasy"),
                            ("SCI_FI", "Science Fiction"),
                            ("HORROR", "Horror"),
                            ("MYSTERY", "Mystery"),
                            ("HISTORICAL", "Historical"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "theme_keywords",
                    models.CharField(
                        help_text="Comma-separated keywords", max_length=200
                    ),
                ),
                (
                    "cultural_references",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated references",
                        max_length=200,
                    ),
                ),
                ("universe_description", models.TextField()),
                ("story_description", models.TextField()),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the game is visible to other users",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("background", models.TextField()),
                ("abilities", models.TextField()),
                ("motivation", models.TextField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="games.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="game_images/")),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("CHARACTER", "Character"),
                            ("ENVIRONMENT", "Environment"),
                            ("CONCEPT", "Concept Art"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="games.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="games.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "game")},
            },
        ),
    ]
