# Generated by Django 5.2.1 on 2025-05-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameproject',
            name='interactive_story',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
